version: '3.8'

services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb/
    expose:
      - "3306"
    volumes:
      - mariadb_vol:/var/lib/mysql/
    networks:
      - inception 
    env_file: .env
    init: true
    restart: on-failure

  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress/
    expose:
      - "9000"
    volumes:
      - wordpress_vol:/var/www/wordpress/
    networks:
      - inception
    env_file: .env
    init: true
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    image: nginx:inception
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_DIR: ${CERT_DIR}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - '443:443'
    volumes:
      - wordpress_vol:/var/www/wordpress/
    networks:
      - inception
    env_file: .env
    init: true
    restart: on-failure
    depends_on:
      - wordpress

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsodre-p/data/mariadb_vol

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsodre-p/data/wordpress_vol
networks:
  inception:
    driver: bridge