version: '3.8'
services:
    mariadb:
      image: mariadb:42
      container_name: mariadb
      build: ./requirements/mariadb/
      expose:
        - "3306" # Expose port 3306 to other services
      volumes:
        - mariadb:/var/lib/mysql/
      networks:
        - inception # Custom network
      env_file: .env # Inject variables into the env of the container
      init: true
      restart: on-failure
    
    wordpress:
      image: wordpress:inception
      build: ./requirements/wordpress
      container_name: wordpress
      restart: on-failure
      depends_on:
        - mariadb
      expose:
        - 9000
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html
      init: true

    nginx:
      image: nginx:inception
      build: 
        context: ./requirements/nginx
        args:
        - SCHOOL_USERNAME
        - DOMAIN_NAME
        - NGINX_CERT
        - NGINX_KEY
        - CERT_DIR
      container_name: nginx
      restart: on-failure
      depends_on:
        - mariadb
        - wordpress
      ports:
        - 443:443
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html
      init: true

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress
      o: bind