version: '3.8'
services:
    nginx:
      build: 
        context: ./requirements/nginx
        args:
        - SCHOOL_USERNAME
        - DOMAIN_NAME
        - NGINX_CERT
        - NGINX_KEY
      container_name: nginx
      restart: always
      depends_on:
        - mariadb
        - wordpress
      ports:
        - 443:443
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html
    
    mariadb:
      build: ./requirements/mariadb
      container_name: mariadb
      restart: always
      expose:
        - 3306
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - mariadb:/var/lib/mysql
    
    wordpress:
      build: ./requirements/wordpress
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      expose:
        - 9000
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - wordpress:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  nginx:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/nginx
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/${USERNAME}/data/wordpress
      o: bind